blog_flask/articles/views.py
from typing import Dict

import requests as requests
from flask import Blueprint, render_template, redirect, request, url_for
from flask_login import login_required, current_user
from sqlalchemy.orm import joinedload
from werkzeug.exceptions import NotFound

from blog_flask.config import db
from blog_flask.forms.article import CreateArticleForm
from blog_flask.models import Article, Author, Tag

articles = Blueprint('articles', __name__, url_prefix='/articles', static_folder='../static')


@articles.route('/', methods=['GET'])
def article_list():
    articles: Article = Article.query.all()
    count_articles: Dict = requests.get('http://127.0.0.1:5000/api/articles/event_get_count/').json()
    return render_template(
        'articles/list.html',
        articles=articles,
        count_articles=count_articles['count'],
    )


@articles.route('/<int:article_id>/', methods=['GET'])
def articles_info(article_id):
    _article: Article = Article.query.filter_by(
        id=article_id
    ).options(
        joinedload(Article.tags)
    ).one_or_none()

    if _article is None:
        raise NotFound
    return render_template(
        'articles/detail.html',
        article=_article,
    )


@articles.route('/create/', methods=['GET'])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    return render_template('articles/create.html', form=form)


@articles.route('/', methods=['POST'])
@login_required
def create_article():
    form = CreateArticleForm(request.form)

    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]

    if form.validate_on_submit():
        _article = Article(title=form.title.data.strip(), text=form.text.data)
        if current_user.author:
            _article.author_id = current_user.author.id
        else:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            _article.author_id = author.id

        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tags.append(tag)

        db.session.add(_article)
        db.session.commit()

        return redirect(url_for('articles.articles_info', article_id=_article.id))

    return render_template('articles/create.html', form=form)

blog_flask/authors/views.py
from flask import Blueprint, render_template

from blog_flask.models import Author

authors = Blueprint('authors', __name__, url_prefix='/authors', static_folder='../static')


@authors.route('/')
def author_list():
    authors = Author.query.all()
    return render_template(
        'authors/list.html',
        authors=authors,
    )

blog_flask/users/views.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import current_user, login_user
from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash

from blog_flask.config import db
from blog_flask.forms.user import UserRegisterForm
from blog_flask.models import Users

users = Blueprint('users', __name__, url_prefix='/users', static_folder='../static')


@users.route('register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users.get_user', pk=current_user.id))

    form = UserRegisterForm(request.form)
    errors = []
    if request.method == 'POST' and form.validate_on_submit():
        if Users.query.filter_by(email=form.email.data).count():
            form.email.errors.append('email already exists')
            return render_template('users/register.html', form=form)

        _user = Users(
            email=form.email.data,
            name=form.name.data,
            password_hash=generate_password_hash(form.password.data),
        )

        db.session.add(_user)
        db.session.commit()

        login_user(_user)

    return render_template(
        'users/register.html',
        form=form,
        errors=errors,
    )


@users.route('/')
def user_list():
    users = Users.query.all()
    return render_template(
        'users/list.html',
        users=users,
    )


@users.route('/<int:pk>')
def get_user(pk: int):
    user = Users.query.filter_by(id=pk).one_or_none()

    if user is None:
        raise NotFound(f'User #{pk} does not exist!')

    return render_template(
        'users/detail.html',
        user=user
    )

blog_flask/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block css %}
    <!-- Bootstrap CSS -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
  {% block body %}{% endblock %}
</div>


{% block js %}
    <script src="{{ url_for('static', filename='bootstrap.bundle.min.js') }}"></script>
{% endblock %}
</body>
</html>

blog_flask/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.user_list') }}">Пользователи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('authors.author_list') }}">Авторы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('articles.article_list') }}">Статьи</a>
                </li>

                <li class="nav-item">
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('articles.create_article_form') }}">Создание статьи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Выйти ({{ current_user.name }})</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Войти</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.register') }}">Регистрация</a>
                </li>
                </li>
            </ul>
        </div>
    </div>
</nav>